//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMC.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RepositoryResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RepositoryResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MMC.Data.RepositoryResource", typeof(RepositoryResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BUNDLED.
        /// </summary>
        internal static string BUNDLED {
            get {
                return ResourceManager.GetString("BUNDLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to easy.
        /// </summary>
        internal static string EASY {
            get {
                return ResourceManager.GetString("EASY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to extreme.
        /// </summary>
        internal static string EXTREME {
            get {
                return ResourceManager.GetString("EXTREME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hard.
        /// </summary>
        internal static string HARD {
            get {
                return ResourceManager.GetString("HARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to medium.
        /// </summary>
        internal static string MEDIUM {
            get {
                return ResourceManager.GetString("MEDIUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SINGLE.
        /// </summary>
        internal static string SINGLE {
            get {
                return ResourceManager.GetString("SINGLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smartphone.
        /// </summary>
        internal static string SMARTPHONE {
            get {
                return ResourceManager.GetString("SMARTPHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tablet.
        /// </summary>
        internal static string TABLET {
            get {
                return ResourceManager.GetString("TABLET", resourceCulture);
            }
        }
    }
}
